---
title: "R Notebook"
output: html_notebook
---


```{r}
require(tidyverse)
require(GA)
require(broom)

retModelOut <- function (time, params) {
  a <- params[1]
  b <- params[2]
  g <- params[3]
  Cnot <- params[4]
  kOne <- params[5] - b*Cnot/(a - b + g)
  nGrowth <- Cnot*exp((a - b)*time)
  psGrowth <- b*nGrowth/(a - b + g) + kOne*exp(-g*time)
  
  return(data.frame(ElapsedM = time, ConflM = nGrowth, AnnexinM = psGrowth))
}

retModelOut <- compiler::cmpfun(retModelOut)
```


# x[0] normal cells
# x[1] apoptotic cells

```{r}
modelFit <- function (dataIn, params) {
  dataMod <- cbind(retModelOut(dataIn$Elapsed, params), dataIn)
  
  return(mutate(dataMod, llConfl = dnorm(Confl, mean = ConflM, sd = params[6]*ConflM, log = T), 
                llAnn = dnorm(Annexin, mean = AnnexinM, sd = params[6]*AnnexinM, log = T)))
}

modelLL <- function (dataIn, params) {
  dataMod <- modelFit(dataIn, 10.^params)
  LL <- sum(dataMod$llConfl) + sum(dataMod$llAnn)

  if (is.infinite(LL)) {LL <- -30000000}
  return(LL)
}

runFit <- function (dataIn) {
  x <- ga(type = "real-valued", fitness = function(xIn) modelLL(dataIn, xIn), 
          min = c(-3, -6, -2, 0, -2, -4), max = c(0, 0, -2, 2, 0, 1), popSize = 50, maxiter = 50, optim = T, parallel = T, monitor = F)
  return(x@solution)
}

rebuildF = function (inn) {
  datt <- retModelOut(seq(0, 72, 0.1), 10.^as.numeric(inn[2:7])) %>% mutate(Condition = inn[1])
  return(datt)
}
```


We'll fit this model to the data of H1299 cells treated with various cytotoxic agents.

```{r}
loadData <- function () {
  data <- read_csv("091916_H1299_cytotoxic_confluence_confl.csv") %>% 
    reshape2::melt(id.vars = c("Time", "Elapsed"), value.name = "Confl", variable.name = "Condition") %>% 
    select(-Time)
  data_green <- read_csv("091916_H1299_cytotoxic_confluence_green.csv") %>% 
    reshape2::melt(id.vars = c("Time", "Elapsed"), value.name = "Annexin", variable.name = "Condition") %>%
    select(Annexin)
  
  data <- cbind(data, data_green)
  return(data)
}

data <- loadData() %>% filter(Condition != "blank")
```


Now we run the fitting process against the data.

```{r}
outt <- data %>% group_by(Condition) %>% do(tidy(runFit(.))) %>% mutate(divisionRate = x1, apoptosisRate = x2)

modelOut <- do.call("rbind", apply(outt, 1, rebuildF))
```

```{r}
ggplot() + geom_point(aes(x = Elapsed, y = Confl, color = Condition), data = data) + 
  geom_point(aes(x = Elapsed, y = Annexin, color = Condition), data = data, shape = 2) + 
  geom_line(aes(x = ElapsedM, y = AnnexinM, color = Condition), data = modelOut) + 
  geom_line(aes(x = ElapsedM, y = ConflM, color = Condition), data = modelOut) + scale_y_log10()
```

```{r}
outt <- outt %>% separate(Condition, c("Drug", "Conc", "Units"), fill = "right", convert = T, sep = " ", remove = F) %>%
  select(-Units) %>% mutate(Drug = as.factor(Drug)) %>%
  filter(Drug != "blank")

ggplot(outt, aes(x = divisionRate, y = apoptosisRate, color = Drug)) + geom_point()
```
